name: Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}, Buildout ${{ matrix.buildout-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
      matrix:
        os: [ 'ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-22.04' ]
        python-version: [ '3.9', '3.10' ]
        buildout-version: ['2.13.7', '3.0.0rc3']

    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup environment and run Buildout
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install --upgrade --pre "zc.buildout==${{ matrix.buildout-version }}"
          buildout -vv -n -c base.cfg
