name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
      matrix:
        os: [ 'macos-10.15', 'macos-11', 'macos-12' ]
        python-version: [ '3.9', '3.10' ]

    steps:

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SQLAlchemy
        run: |
          pip install sqlalchemy
